// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AbuseError is an autogenerated mock type for the AbuseError type
type AbuseError struct {
	mock.Mock
}

// Details provides a mock function with given fields:
func (_m *AbuseError) Details() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Details")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *AbuseError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewAbuseError creates a new instance of AbuseError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAbuseError(t interface {
	mock.TestingT
	Cleanup(func())
}) *AbuseError {
	mock := &AbuseError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
